name: tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mini_wallet_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d mini_wallet_test -h localhost -p 5432"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

    env:
      DB_CONNECTION: pgsql
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_DATABASE: mini_wallet_test
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      APP_ENV: testing

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm ci

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate Application Key
        run: php artisan key:generate --ansi

      - name: Wait for Postgres
        run: |
          echo "Waiting for Postgres to accept connections..."
          php -r '
          $tries = 0;
          while ($tries++ < 30) {
              try {
                  $pdo = new PDO("pgsql:host=127.0.0.1;port=5432;dbname=mini_wallet_test", "postgres", "postgres", [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
                  exit(0);
              } catch (Exception $e) {
                  usleep(500000);
              }
          }
          echo "Postgres did not start in time\n";
          exit(1);
          '
      - name: Build Assets
        run: npm run build

      - name: Tests
        run: ./vendor/bin/pest --colors=always
